package com.example.decalxeandroid.domain.model

data class Order(
    val orderId: String,
    val orderNumber: String,
    val customerId: String,
    val customerFullName: String,
    val vehicleId: String?,
    val vehicleLicensePlate: String?,
    val assignedEmployeeId: String?,
    val assignedEmployeeName: String?,
    val orderStatus: String,
    val currentStage: String,
    val totalAmount: Double,
    val depositAmount: Double,
    val remainingAmount: Double,
    val orderDate: String,
    val expectedCompletionDate: String?,
    val actualCompletionDate: String?,
    val notes: String?,
    val isActive: Boolean,
    val createdAt: String,
    val updatedAt: String?,
    // Additional properties from OrderDto
    val chassisNumber: String?,
    val vehicleModelName: String?,
    val vehicleBrandName: String?,
    val expectedArrivalTime: String?,
    val priority: String?,
    val isCustomDecal: Boolean,
    val storeId: String?,
    val description: String?,
    val customerPhoneNumber: String?,
    val customerEmail: String?,
    val customerAddress: String?,
    val accountId: String?,
    val accountUsername: String?,
    val accountCreated: Boolean?
)
